"""unificate file_url

Revision ID: 0ddd3a78a8d4
Revises: 30b7ea6148b0
Create Date: 2025-03-21 13:01:06.676483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddd3a78a8d4'
down_revision: Union[str, None] = '30b7ea6148b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_entries', 'file_url')
    op.add_column('photos', sa.Column('diary_entry_id', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('file_url', sa.String(), nullable=False))
    op.drop_constraint('photos_diary_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'diary_entries', ['diary_entry_id'], ['id'])
    op.drop_column('photos', 'diary_id')
    op.drop_column('photos', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('photos', sa.Column('diary_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_diary_id_fkey', 'photos', 'diary_entries', ['diary_id'], ['id'])
    op.drop_column('photos', 'file_url')
    op.drop_column('photos', 'diary_entry_id')
    op.add_column('diary_entries', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
