"""Add file_url to diary_entries

Revision ID: 5aa43bf4c302
Revises: c7b86533323f
Create Date: 2025-03-18 13:34:10.585407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa43bf4c302'
down_revision: Union[str, None] = 'c7b86533323f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_entries', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_entries', 'file_url')
    # ### end Alembic commands ###
