"""Add Photo model

Revision ID: c7b86533323f
Revises: e76fd7999da6
Create Date: 2025-03-18 13:11:52.728899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b86533323f'
down_revision: Union[str, None] = 'e76fd7999da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('diary_id', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('file_path', sa.String(), nullable=True))
    op.drop_constraint('photos_diary_entry_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'diary_entries', ['diary_id'], ['id'])
    op.drop_column('photos', 'diary_entry_id')
    op.drop_column('photos', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('photos', sa.Column('diary_entry_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_diary_entry_id_fkey', 'photos', 'diary_entries', ['diary_entry_id'], ['id'])
    op.drop_column('photos', 'file_path')
    op.drop_column('photos', 'diary_id')
    # ### end Alembic commands ###
